### ISSUE TITLE
Linking to an internal section

### ISSUE THREAD

**Issue by jim-rosales** [derekjcerretani/teacozy#3]
For these links if you make use of ids for each of the links respective section you can add anchor links that take the user to each section when linked.

For example for the mission section:
```HTML
    <div id="mission">
      <div class="mission image-content">
        <div class="text-content">
          <h2>Our Mission</h2>
          <h4>Handpicked, Artisanly Curated, Free Range, Sustainable, Small Batch, Fair Trade, Organic Tea</h4>
        </div>
      </div>
    </div>
```

Then the link can be updated to:

```HTML
        <span><a href="#mission">Mission</a></span>
```

If you take this approach you will need to update your CSS file by targeting the new mission id instead of the class
```CSS
#mission {
  width: 100%;
  display: flex;
  justify-content: center;
  align-items: center;
}
```

https://github.com/derekjcerretani/teacozy/blob/e0f369e1658c60ed531afe5a8d0b4f3d4f90da50/index.html#L17-L19
